### ISSUE TITLE
node_child_process is not defined when running inside electron app

### ISSUE THREAD

**Issue by loukaspd** [obaydmerz/powerjs#1] opened 2023-10-28 15:37 UTC
Hello,

I'm trying to build an electron app that runs powershell commands underneath.
When I'm initializing a PowerJS instance I get the following error
```
node_child_process is not defined
```

---
- I'm using version "1.0.0"
- building the app with yarn
- electron version "21.4.4"

**Comment by xipid** [comment] 2023-12-07 15:21
Hello @loukaspd ,

I apologize for the delay in my response.

I noticed that you are using an older version of Node, where the `node:` prefix is not available to import built-in modules like `child_process`.

In my code, I originally wrote:

```javascript
import { spawn } from "node:child_process";
```

However, I have since removed the node: prefix, and it should work now.
Here's the **[commit](https://github.com/obaydmerz/powerjs/commit/9c97c1c90af2591afd3d91558d82a04d584ed242)**.

Please try reinstalling the library and check if it resolves the issue.
**Note:** I haven't published this to NPM; it's only available on GitHub.

**Comment by rsmarples** [comment] 2023-12-12 13:46
I can confirm the master branch works in Electron-28

**Comment by xipid** [comment] 2023-12-28 17:35
confirmed that this issue is fixed in the new code

**Closed as completed** 2023-12-28 17:35 UTC
